
services:
  - type: web
    name: aurion-api
    env: docker
    rootDir: apps/backend
    plan: free
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "10000"
