name: 🚀 Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Aurion BIM Backend to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: render-oss/render-deploy-action@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
